### ISSUE TITLE
Setting preferred temperature to celsius has no effect on the brew temp option

### ISSUE THREAD

**Issue by ChausseBenjamin** [erikng/Agile-Brewing-Issues#15]
App version: V1.0 (37)

Upon launching the app, the temperature dial will appear as a celsius minimum. When moving the slider, this value will revert to a value in the Fahrenheit range.

See the following for context:

https://user-images.githubusercontent.com/19275615/177042475-bd7e30b4-ce43-4257-ab0a-a3ad0bf522c4.MOV

**Comment by erikng** [comment]
I cannot recreate this on v41 but I have fixed another bug I found with F/C settings that will be fixed in v42, coming today
