### ISSUE TITLE
pressing the notes icon does nothing

### ISSUE THREAD

**Issue by twocanoes** [erikng/Agile-Brewing-Issues#52]
i kept hitting the notes icon and it didn't do anything. i then realized you had to tap the title. the icon does highlight so it was giving me feedback that it was a button. 

love the app!

**Comment by erikng** [comment]
There is some weird behaviors with multi line text fields on iOS 15 that Apple has fixed with iOS 16. Sadly nothing I can do with this one. On iOS 15 it's secretly a ZStack to mask the other bugs but it is what it is. 

Thanks for the report!
