### ISSUE TITLE
Are the sliders for Dosage, TDS and Actual Yield confusing?

### ISSUE THREAD

**Issue by erikng** [erikng/Agile-Brewing-Issues#7]
So far people don't seem to realize they are sliders like the Timer app on iOS.

I think this has to do with the fact that the timer app shows multiple fields at once, but I don't like how that looks on the app.

If people continue to be confused, perhaps we need an introduction video showing how to use the app, or a gif.

**Comment by ChausseBenjamin** [comment]
Something that could help is allowing users to tap the number and enter the value with a keyboard.

**Comment by erikng** [comment]
Lots of people have issues with this, but I still don't know what the right approach is here

> The data input looks pretty inconsistent to me. The grind size is a drop down menu. The dosage is a scroll wheel. I think a normal text input would be more intuitive. especially for the grind size. e.g. I use a DF64 and want to save more than size 10 or 10.5. I Want to save 10.2 :-)
> 
> The same for the TDS field. I want to just type in the data from my refractometer and dont want to scroll on two wheels.


another

> To me, it doesn’t make sense that you have three different types of information input for numbers. The dose entry is a roller style with decimal, the tamp pressure is a sliding scale, and then shot time is whole number limited selection only. Pick one method and use of for all number entries. There is also an assumption that all grinders only use a scale that is 0.5. Plenty of grinder use 0.1 value steps. Like mine. Makes much more sense to use the number input Mathis you have for dose and yield, to be used for ALL number entry fields.

another

> I will say it took me a solid five minutes to figure out how to change the dose. I’m curious on the choice of having so many different styles of data input, the dragging, the selection, the typing, the bar button drag, so i wanted to hear more about why you made those decisions.

**Comment by erikng** [comment]
My feedback to these people so far

I kept trying different input styles for each type of option and some worked better than others.

Originally for dose it was a single slider but wasn't accurate enough. Then I made two sliders for dose and sub dose and it felt too slow and the dose was still not accurate enough on smaller screen sizes so I then tried the new slide thing I have now.

I get that it may not be consistent, but I find some to be more accurate than others for certain fields.

**Comment by erikng** [comment]
https://github.com/erikng/Agile-Brewing-Issues/issues/13#issuecomment-1212063387

> Selection sliders/menus: there are different types of selecting different numbers: gring size is one, dosage is another type, temperature is a slider. Is there a reason for this diversity? Personally, I don't quirw like the grind selection, dosage, preinfusion, extraction time, and I would rather have them the same style as dosage.

My response: https://github.com/erikng/Agile-Brewing-Issues/issues/13#issuecomment-1213628709

**Comment by erikng** [comment]
I'm going to close this because in the next version v1.0.6 the following changes are being made
- Dosage, Actual Yield are now pull out menus
- TDS is now a decimal keyboard input
